# Generated by Django 2.1.3 on 2018-11-18 05:34

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=250)),
                ('orgao', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('1', 'Denúncia'), ('2', 'Reclamação'), ('3', 'Solicitação'), ('4', 'Sugestão')], default='1', max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('descricao', models.TextField()),
                ('localizacao', djgeojson.fields.PointField()),
            ],
        ),
    ]
