# Generated by Django 2.1.3 on 2018-11-18 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manifestacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifestacao',
            name='highlights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manifestacao',
            name='visibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
