# Generated by Django 2.1.3 on 2018-11-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifestacao', '0002_auto_20181118_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifestacao',
            old_name='localizacao',
            new_name='geom',
        ),
    ]
