# Generated by Django 2.1.3 on 2018-11-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestacao', '0003_auto_20181118_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestacao',
            name='endereco',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
